{% set name = "robotraconteur_companion" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/robotraconteur/robotraconteur_companion.git
  git_rev: v{{ version }}

build:
  number: 1

requirements:
  host:
    - robotraconteur
    - git
    - cmake
    - boost-cpp
    - ninja  # [win]
    - make  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - yaml-cpp
    - eigen
    - openssl
  run:
    - boost-cpp
    - eigen
    - yaml-cpp
    - robotraconteur
    - openssl

test:
  commands:
    - test -f ${PREFIX}/include/RobotRaconteurCompanion/StdRobDef/StdRobDefAll.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\RobotRaconteurCompanion\\StdRobDef\\StdRobDefAll.h (exit 0) else (exit 1)  # [win]

about:
  home: http://robotraconteur.com
  dev_url: https://github.com/robotraconteur/robotraconteur_companion
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Companion library for the Robot Raconteur core library'

extra:
  recipe-maintainers:
    - johnwason
