package:
  name: robotraconteur_companion
  version: 0.2.0

source:
  git_url: https://github.com/robotraconteur/robotraconteur_companion.git
  git_rev: v0.2.0

requirements:
  host:
    - robotraconteur
    - git
    - cmake
    - boost-cpp
    - ninja # [win]
    - make # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - yaml-cpp
    - eigen
    - openssl
  run:
    - boost-cpp
    - eigen
    - yaml-cpp
    - robotraconteur
    - openssl

build:
  number: 1

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: 'Companion library for the Robot Raconteur core library'

