{% set name = "robotraconteur_companion" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/robotraconteur/robotraconteur_companion/archive/v{{ version }}.tar.gz
    sha256: cfcf199d1187b30fdd83b5e61e4113da6d819f61a032cfc4ccd5fa463c3d3ef1
  - url: https://github.com/robotraconteur/robotraconteur_standard_robdef/archive/refs/tags/group1-v1.tar.gz
    sha256: aad4f122b1240756564d6f3d16258e3fd07febad9e0ceda489c5e32290e64707
    folder: robdef

build:
  number: 3

requirements:
  build:
    - git
    - cmake
    - ninja  # [win]
    - make  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - robotraconteur
    - libboost-devel
    - yaml-cpp
    - eigen
    - openssl  # [unix]
    - zlib # [unix]
  run:
    - eigen
    - yaml-cpp
    - zlib # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/RobotRaconteurCompanion/StdRobDef/StdRobDefAll.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\RobotRaconteurCompanion\\StdRobDef\\StdRobDefAll.h (exit 0) else (exit 1)  # [win]
    - test -f ${PREFIX}/lib/libRobotRaconteurCompanion.a  # [linux]
    - test -f ${PREFIX}/lib/libRobotRaconteurCompanion.a  # [osx]
    - if exist %PREFIX%\\Library\\lib\\libRobotRaconteurCompanion.lib (exit 0) else (exit 1)  # [win]

about:
  home: http://robotraconteur.com
  dev_url: https://github.com/robotraconteur/robotraconteur_companion
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Companion library for the Robot Raconteur core library'

extra:
  recipe-maintainers:
    - johnwason
